@startuml
' to see the result, visit https://kroki.io/plantuml/svg/eNqVkUFrAkEMhe_7K3Jc_0KFFlHoTYR66TG4md3QOFOTrOK_d1ZQ1C47NIdhCO8x33tjjuoVB6hXiQzYwYYNnNg7QBByJ4V3OHzMwDuKUH-TzSrIUzbZX9OrURPquGqYty23pPP7jsQI6nV6VSX1xEYPwthwqMYtj88LHwn62GTcE2boCZSvQ89NEWVQqZKMolxvz8ZyiaFcYoc5haTYQqTdz0SGT1YMgYopNoJ-_u3t_4USZpx-j9EmMBYi3KKn8s8uEwnuMHo3UejtvABpfbw6
start
if (Does it start with a letter > q?) then (Yes)
    if (Does it start with a letter > s?) then (Yes)
        if (Does it roar?) then (Yes)
            :Tiger;
        else (No)
            :Tortoise;
        endif
    else (No)
        if (Does it live under water?) then (Yes)
            :Squid;
        else (No)
            :Squirrel;
        endif
    endif
else (No)
    if (Does it start with a letter > f?) then (Yes)
        if (Does it have long neck?) then (Yes)
            :Giraffe;
        else (No)
            :Platypus;
        endif
    else (No)
        if (Does it eat humans?) then (Yes)
            :Alligator;
        else (No)
            :Coelacanth;
        endif
    endif
endif
end
@enduml
